name: PPAP
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.3.1
  - pytorch-lightning=2.1.4
  - torchmetrics=0.9.3
  - h5py>=3.11.0
  - pip
  - pip:
      - fair-esm==2.0.0
      - torch-scatter==2.1.2
      - torch-geometric==2.5.3
      - biopython==1.83
